blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('produto', views.produto_list, name='produto_list'),
    path('produto/<int:pk>/', views.detail_prod, name='detail_prod'),
    path('add/', views.ProdutoCreate.as_view(), name='produto_add'),
    path('add/submit', views.produto_submit, name='produto_submit'),
    path('<int:pk>/edit/submit', views.detail_prod, name='detail_prod'),
    

    path('<int:pk>/edit/', views.ProdutoUpdate.as_view(), name='produto_edit'),
    path('produto/<int:pk>/json/', views.produto_json, name='produto_json'),
    path('estoque', views.ent_estoque, name='ent_estoque'),
    path('estoque/<int:pk>/', views.ent_estoque_detail, name='ent_estoque_detail'),
    path('estoque/add/', views.ent_estoque_form, name='ent_estoque_form'),
    path('estoque/saida/', views.sai_estoque, name='sai_estoque'),
    path('estoque/saida/<int:pk>/', views.sai_estoque_detail, name='sai_estoque_detail'),
    path('saida/', views.sai_estoque_form, name='sai_estoque_form'),
    path('login/', views.login_user),
    path('login/submit', views.submit_login),
    path('logout/', views.logout_user),

    path('parceiro/', views.parceiro_list, name='parceiro_list'),
    path('parceiro/<int:pk>/', views.parceiro_detail, name='parceiro_detail'),
    path('parceiro/add/', views.ParceiroCreate.as_view(), name='parceiro_add'),
    path('parceiro/<int:pk>/edit/', views.ParceiroUpdate.as_view(), name='parceiro_edit'),



]   

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    

]

blog/models.py
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy


TIPOPARCEIRO = (
    ('Fornecedor', 'Fornecedor'),
    ('Cliente', 'Cliente'),
    ('Funcionário', 'Funcionário'),
    )
ESTADO = (
           ('AC', 'Acre'),
           ('AL', 'Alagoas'),
           ('AP', 'Amapá'),
           ('AM', 'Amazonas'),
           ('BA', 'Bahia'),
           ('CE', 'Ceará'),
           ('DF', 'Distrito Federal'),
           ('ES', 'Espírito Santo'),
           ('GO', 'Goiás'),
           ('MA', 'Maranhão'),
           ('MT', 'Mato Grosso'),
           ('MS', 'Mato Grosso do Sul'),
           ('MG', 'Minas Gerais'),
           ('PA', 'Pará'),
           ('PB', 'Paraíba'),
           ('PR', 'Paraná'),
           ('PE', 'Pernambuco'),
           ('PI', 'Piauí'),
           ('RJ', 'Rio de Janeiro'),
           ('RS', 'Rio Grande do Sul'),
           ('RO', 'Rondônia'),
           ('RR', 'Roraima'),
           ('SC', 'Santa Catarina'),
           ('SP', 'São Paulo'),
           ('SE', 'Sergipe'),
           ('TO', 'Tocantins'),
           )
class Parceiro (models.Model):
    parceiro = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=14)
    inscricao_estadual = models.CharField(max_length=50)
    contato = models.CharField(max_length=100)
    telefone = models.CharField(max_length=11)
    email = models.EmailField(max_length=300)
    rua = models.CharField(max_length=300)
    numero = models.CharField(max_length=9)
    cep = models.CharField(max_length=9)
    bairro = models.CharField(max_length=60)
    cidade = models.CharField(max_length=60)
    estado = models.CharField(max_length=15, choices=ESTADO)
    tipo_parceiro = models.CharField(max_length=50, choices=TIPOPARCEIRO)
    observacao = models.TextField()
    
    class meta:
        ordering= ('parceiro',)
    
    def __str__(self):
        return str(self.parceiro)

    def get_absolute_url(self):
        return reverse_lazy('blog:parceiro_detail', kwargs={'pk': self.pk})


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class TimeStampedModel (models.Model):
    created = models.DateTimeField(
         'Criado em ',
         auto_now_add=True,
         auto_now=False
    )
    modified = models.DateTimeField(
        'Modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

TIPOPRODUTO = (
    ('Produto Acabado','Produto Acabado'),
    ('Matéria Prima','Matéria Prima'),
)
class Produto (models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100)
    preco = models.DecimalField ('Preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('Estoque Minímo', default=0)
    tipo_produto = models.CharField(max_length=30, choices=TIPOPRODUTO, blank=True)

    class meta:
        ordering= ('produto')

    def __str__(self):
        return str(self.produto)

    def get_absolute_url(self):
        return reverse_lazy('blog:detail_prod', kwargs={'pk': self.pk})
    
    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }

MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saida'),
)

class Estoque (TimeStampedModel):
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO, blank=True)
    parceiro = models.ForeignKey(Parceiro, on_delete=models.CASCADE, )

    class meta:
        ordenring = ('-created') 

    def __str__(self):
        if self.nf:
            return '{} - {} - {}'.format(self.pk, self.nf, self.created.strftime('%d-%m-%Y'))
        return '{} --- {}'.format(self.pk,self.created.strftime('%d-%m-%Y'))

    def nf_formated(self):
        if self.nf:
            return str (self.nf).zfill(3)
        return '---'

class EstoqueEntradaManeger(models.Manager):
    def get_queryset(self):
        return super(EstoqueEntradaManeger, self).get_queryset().filter(movimento = 'e')

class EstoqueEntrada(Estoque):
    objects = EstoqueEntradaManeger()
    class Meta:
        proxy = True
        verbose_name = 'estoque entrada'
        verbose_name_plural = 'estoque entrada' 
    def get_absolute_url(self):
        return reverse_lazy('blog:ent_estoque_detail', kwargs={'pk': self.pk})

class EstoqueSaidaManeger(models.Manager):
    def get_queryset(self):
        return super(EstoqueSaidaManeger, self).get_queryset().filter(movimento = 's')

class EstoqueSaida(Estoque):
    objects = EstoqueSaidaManeger()
    class Meta:
        proxy = True
        verbose_name = 'estoque saida'
        verbose_name_plural = 'estoque saida' 
    
    def get_absolute_url(self):
        return reverse_lazy('blog:sai_estoque_detail', kwargs={'pk': self.pk})

class EstoqueItens(models.Model):
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, related_name='estoques')
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField(blank=True)

    class Meta:
        ordering=('pk',)

    def __str__(self):
        return '{} - {} - {}'.format (self.pk, self.estoque.pk, self.produto)

    

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import  authenticate, login, logout
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, resolve_url, redirect
from django.views.generic import CreateView, UpdateView
from django.utils import timezone
from django.forms import inlineformset_factory
from django.views.decorators.csrf import csrf_protect
from .models import Produto,Estoque, EstoqueEntrada, EstoqueSaida, EstoqueItens, Parceiro
from .form import ProdutoForm, EstoqueForm, EstoqueItensForm, ParceiroForm


@login_required(login_url='/login/')
def index(request):
    #posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date') 
    #return render(request, 'blog/post_list.html', {'posts': posts})
    return render(request, 'blog/index.html')
    
def post_list (request):
    return render(request, 'blog/post_list.html')

def produto_list (request):
    template_name = 'blog/produto_list.html'
    objects = Produto.objects.all()
    search =   request.GET.get('search')
    if search:
        objects = objects.filter(produto__icontains=search)
    context = {'object_list': objects}
    return render( request, template_name, context)

def detail_prod (request, pk):
    template_name = 'blog/detail_prod.html'
    codigoP = Produto.objects.get(pk=pk)
    context = {'object': codigoP}
    return render( request, template_name, context)

def produto_add(request):
    template_name= 'blog/form_prod.html'
    return render (request, template_name)

def produto_submit(request):
    importado = request.POST.get('importado')
    ncm = request.POST.get('ncm')
    produto = request.POST.get('produto')
    preco = request.POST.get('preco')
    estoque = request.POST.get('estoque')
    estoque_minimo = request.POST.get('estoque_minimo')
    tipo_produto = request.POST.get('tipo_parceiro')
    codigoP = request.POST.get('cod')
    prod = Produto.objects.create( importado=importado, ncm=ncm, produto=produto,preco=preco,
    estoque=estoque, estoque_minimo=estoque_minimo, tipo_produto=tipo_produto,)
    url = '/'
    return redirect(url)

class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'blog/form_prod.html'
    form_class = ProdutoForm

class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'blog/form_prod.html'
    form_class = ProdutoForm

def ent_estoque (request):
    template_name = 'blog/estoque_list.html'
    objects = EstoqueEntrada.objects.all()
    search =   request.GET.get('search')
    if search:
        objects = objects.filter(nf__icontains=search)
    context = {'object_list':objects,'titulo':'Entrada','url_add':'blog:ent_estoque_form'}

    return render (request, template_name, context) 
    
def ent_estoque_detail (request, pk):
    template_name = 'blog/estoque_detail.html'
    obj = EstoqueEntrada.objects.get(pk=pk)
    context = {'object':obj, 'url_list':'blog:ent_estoque',}
    return render (request, template_name, context) 

def dar_baixa_estoque(form):
    # Pega os produtos a partir da instância do formulário (Estoque).
    produtos = form.estoques.all()
    for item in produtos:
        produto = Produto.objects.get(pk=item.produto.pk)
        produto.estoque = item.saldo
        produto.save()
    print('Estoque atualizado com sucesso.')

def estoque_add(request, template_name, movimento, url):
    estoque_form = Estoque()
    item_estoque_formset = inlineformset_factory(
    Estoque,
    EstoqueItens,
    form = EstoqueItensForm,
    extra = 0,
    can_delete = False,
    min_num = 1,
    validate_min = True,
    )
    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance= estoque_form, prefix = 'main')
        formset = item_estoque_formset(request.POST, instance= estoque_form, prefix= 'estoque')
        if form.is_valid() and formset.is_valid():
            form = form.save(commit=False)
            form.funcionario = request.user
            form.movimento = movimento
            form.save()
            formset.save()
            dar_baixa_estoque(form)
            return {'pk': form.pk}
    else:
        form = EstoqueForm(instance= estoque_form, prefix = 'main')
        formset = item_estoque_formset(instance= estoque_form, prefix= 'estoque')
    context = {'form':form, 'formset':formset}
    return context

def ent_estoque_form (request):
    template_name = 'blog/ent_estoque_form.html'
    movimento = 'e'
    url = 'blog:ent_estoque_detail'
    context = estoque_add(request, template_name, movimento, url)
    if context.get('pk'):
        return HttpResponseRedirect(resolve_url(url, context.get( 'pk')))
    return render (request, template_name, context) 

def produto_json(request, pk):
    #''' Retorna o produto, id e estoque. '''
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})

def sai_estoque_detail (request, pk):
    template_name = 'blog/estoque_detail.html'
    obj = EstoqueSaida.objects.get(pk=pk)
    context = {'object':obj, 'url_list':'blog:sai_estoque'}
    return render (request, template_name, context) 

def sai_estoque (request):
    template_name = 'blog/estoque_list.html'
    objects = EstoqueSaida.objects.all()
    search =   request.GET.get('search')
    if search:
        objects = objects.filter(nf__icontains=search)
    context = {'object_list':objects, 'titulo':'Saída', 'url_add':'blog:sai_estoque_form'}
    return render (request, template_name, context) 
  
def sai_estoque_form (request):
    template_name = 'blog/sai_estoque_form.html'
    movimento = 's'
    url = 'blog:sai_estoque_detail'
    context = estoque_add(request, template_name, movimento, url)
    if context.get('pk'):
        return HttpResponseRedirect(resolve_url(url, context.get( 'pk')))
    return render (request, template_name, context) 

def logout_user (request):
    logout (request)
    return redirect ('/login/')

def login_user (request):
    return render (request, 'blog/login.html')
csrf_protect
def submit_login (request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate (username = username, password = password)
        if user is not None:
            login (request, user)
            return redirect ('/')
        else:
            messages.error (request, 'Usuário ou senha Inválido. Tente novamente')
    return redirect ('/login/')

def parceiro_list (request):
    template_name = 'blog/parceiro_list.html'
    objects = Parceiro.objects.all()
    search =   request.GET.get('search')
    if search:
        objects = objects.filter(parceiro__icontains=search)
    context = {'object_lista': objects}
    return render( request, template_name, context)

def parceiro_detail (request, pk):
    template_name = 'blog/parceiro_detail.html'
    codigo = Parceiro.objects.get(pk=pk)
    context = {'object_par': codigo}
    return render( request, template_name, context)

def parceiro_add(request):
    template_name = 'blog/parceiro_form.html'
    return render(request, template_name)

class ParceiroCreate(CreateView):
    model = Parceiro
    template_name = 'blog/parceiro_form.html'
    form_class = ParceiroForm

class ParceiroUpdate(UpdateView):
    model = Parceiro
    template_name = 'blog/parceiro_form.html'
    form_class = ParceiroForm

blog/templates/blog/Header.html
{% extends "blog/base.html" %}

{% block css%} 
{% endblock css%}

{% block content %} 
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<html>
<head>

    <meta charset="utf-8">
    <title>Financezy</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="shortcut icon" type="image/jpeg" href="{% static "img/logo1.jpeg" %}"/>

    <style>
        body{background-color: #7D979D;}
        nav {
    width: 90%;}
        .page-header{
            margin-left: 135px;}
        
            .ok{
        color: green;
    }
    .no{
        color: red;
    }

    </style>
    {% block css%} {% endblock css%}
</head>

<body>
    <div class="container-fluid">
        <div id = "div1" class="row"><p></p>
            <div class="col-md-12">
            </div>
        </div>
        <div id = "div3" class="row" class="col-md-12">
            <div id = "div3" class="col-md-2">
                <img src="{% static "img/logo1.jpeg" %}" alt = "logo1" width = "100"align = "left"/>
            </div>
            <div id = "div3" class="col-md-8">	
            </div>
            <div id = "div3" class="col-md-2">
                <nav>
                    <ul class="menu">
                        <li><a href="/logout/"> <img src="{% static "img/sair1.png" %}" alt = "sair1" width = "20"/> </a></li>
                        
                        <li><a href="#"> <img src="{% static "img/conf4.png" %}" alt = "conf4" width = "20"/>  </a>
                        </li>
                        <li><a href="{% url 'blog:index' %}"> <img src="{% static "img/home3.png" %}" alt = "home3" width = "20"/> </a></li>
                        
                    </ul>
                </nav>
            </div>
        </div>
        <div id = "div1" class="row" >
            <div class="col-md-12">
            </div>
            <div class="col-md-12">
            </div>
        </div>
    </div>	
    <div>
		<input type="checkbox" id= "check" >
		<label id = "icone" for= "check" style="width:70px;"> <img src = "{% static "img/icone.png" %}"> </label>
		<div class="barra">
			<nav>
				<ul>
				<li><a href="#"><div class = "link"><img src="{% static "img/flux.png" %}" width = "50"/><p>Caixa</div></a></li>
				<li><a href="{% url 'blog:ent_estoque' %}"><div class = "link"><img src="{% static "img/ctapg.png" %}" width = "50"/><p>Despesa</div></a>
    			</li>
				<li><a href="{% url 'blog:sai_estoque' %}"><div class = "link"><img src= "{%static "img/ctare.png" %}" width = "80"/><p>Receita</div></a>
				</li>
				<li><a href="#"><div class = "link"><img src="{% static "img/rel1.png" %}" width = "40"/><p>Cadastro</div></a>
					<ul>
						<li><a href="{% url 'blog:parceiro_list' %}">Parceiro</a></li>
						<li><a href="{% url 'blog:produto_add' %}">Produtos</a></li>
					</ul>
				</li>
				<li><a href="{% url 'blog:produto_list' %}"><div class = "link"><img src="{% static "img/estoque.png" %}" width = "40"/><p>Estoque</div></a></li>
				</ul>
			</nav>
		</div>
    </div>	
    {% block content %} {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    {% block js%}     {% endblock js%}
</body>
</html>

blog/templates/blog/detail_prod.html
{% extends "blog/base.html" %}

{% block css%} 
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<script src=https://kit.fontawesome.com/a076d05399.js></script>


<style>
    #margem {margin-left: 340px;}
    #editar {margin-left: 430;}
    #prod {margin-left: 300;}
</style>

{% endblock css%}


{% block content %} 
<br>
<a id= "margem" href="{% url 'blog:produto_list' %}">
    <button class="btn btn--radius-2 btn--red" >
        <i class="fas fa-backspace"> </i> Voltar 
    </button>
</a>


<span class="pull-rigth">
    <a href="{% url 'blog:produto_edit' object.pk %}">
        <button id = "editar" type="button" class="btn btn-success">
            <span class="fas fa-pencil-alt"></span>Editar

        </button>
    </a>
</span>
<br>

<div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
    <div class="wrapper wrapper--w790">
        <div class="card card-5">
            <div class="card-heading">
                <h1 class="title"> {{object.produto}}</h1>
            </div>
            
                <table class="table table-user-information">
                    <tbody>
                        <tr>
                            <th class="text-rigth">Origem</th>
                            <td>
                                {% if object.importado %}
                                <i class="fa fa-check-circle ok"></i>
                              {% else %}
                                <i class="fa fa-minus-circle no"></i>
                              {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th class="text-rigth">NCM </th>
                            <td> {{object.ncm}}</td>
                        </tr>
                        <tr>
                            <th class="text-rigth">Preço </th>
                            <td> {{object.preco}}</td>
                        </tr>
                        <tr>
                            <th class="text-rigth">Estoque </th>
                            <td> {{object.estoque}}</td>
                        </tr>
                        <tr>
                            <th class="text-rigth">Estoque Mínimo </th>
                            <td> {{object.estoque_minimo}}</td>
                        </tr>
                        <tr>
                            <th class="text-rigth">Categoria Produto </th>
                            <td> {{object.tipo_produto}}</td>
                        </tr>
                    </tbody>    
                </table>
            
            
        </div>
    </div>
</div>

{% endblock content %}

blog/templates/blog/ent_estoque_form.html
{% extends "blog/base.html" %}
{% load bootstrap%}

{% block css%} 
{% load static %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

<style>

    span.required:after{
        content: "*";
        color: red;
    }
    form{
        margin-left: 300px;
        margin-right: 300px;
    }
    .form-control{margin: 10px;} 


    
</style>
{% endblock css%}

{% block content %} 

<br>
><div class="row">
    <div class="col-sm-12">
        <form method="POST" novalidate>
            {% csrf_token %}
            <legend style="border-bottom:1px solid #e5e5e5">Lançamento Despesas</legend>

            <div class="row">
                <div class="col-sm-6">
                    {{form|bootstrap}}
                {{formset.management_form}}
                </div>              
            </div>
            <div class="row">
                <div class="col-sm-12">
                  <legend style="border-bottom: 1px solid #e5e5e5;">Produtos</legend>
                  <div id="estoque" class="form-inline">
                    {% for item_estoque_form in formset %}
                      <div id="item-{{ forloop.counter0 }}" class="form-group">
                        {{ item_estoque_form|bootstrap }}
                      </div>
                    {% endfor %}
                  </div>
                </div>
              </div>
            <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
                <i class="fa fa-plus"></i> Adicionar
            </span>
            
            <div class="row float-rigth">
                <div class="col-sm-12" style="margin-top: 10px;">
                    <div class="form-inline buttons">
                        <button class="btn btn-primary" value="Save">
                            <i class="fa fa-floppy-o"></i>   Salvar 
                        </button>
                        <a href="{% url 'blog:ent_estoque' %}" class="btn btn-danger">
                            <i class="fa fa-times"></i> Cancelar
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

{% block js%}

<script>

    $(document).ready(function() {
      // Insere classe no primeiro item de produto
      $('#id_estoque-0-produto').addClass('clProduto');
      $('#id_estoque-0-quantidade').addClass('clQuantidade');
      // Desabilita o primeiro campo 'Saldo'
      $('#id_estoque-0-saldo').prop('type', 'hidden')
      // Cria um span para mostrar o saldo na tela.
      $('label[for="id_estoque-0-saldo"]').append('<span id="id_estoque-0-saldo-span" class="lead" style="padding-left: 10px;"></span>')
      // Cria um campo com o estoque inicial.
      $('label[for="id_estoque-0-saldo"]').append('<input id="id_estoque-0-inicial" class="form-control" type="hidden" />')
      // Select2
      $('.clProduto').select2()
    });
    
      $('#add-item').click(function(ev) {
        ev.preventDefault();
        var count = $('#estoque').children().length;
        var tmplMarkup = $('#item-estoque').html();
        var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
        $('div#estoque').append(compiledTmpl);
    
        // update form count
        $('#id_estoque-TOTAL_FORMS').attr('value', count + 1);
    
        // Desabilita o campo 'Saldo'
        $('#id_estoque-' + (count) + '-saldo').prop('type', 'hidden')
    
        // some animate to scroll to view our new form
        $('html, body').animate({
          scrollTop: $("#add-item").position().top - 200
        }, 800);
    
        $('#id_estoque-' + (count) + '-produto').addClass('clProduto');
        $('#id_estoque-' + (count) + '-quantidade').addClass('clQuantidade');
    
        // Cria um span para mostrar o saldo na tela.
        $('label[for="id_estoque-' + (count) + '-saldo"]').append('<span id="id_estoque-' + (count) + '-saldo-span" class="lead" style="padding-left: 10px;"></span>')
        // Cria um campo com o estoque inicial.
        $('label[for="id_estoque-' + (count) + '-saldo"]').append('<input id="id_estoque-' + (count) + '-inicial" class="form-control" type="hidden" />')
        // Select2
        $('.clProduto').select2()
      });
    
    let estoque
    let saldo
    let campo
    let campo2
    let quantidade
    
    $(document).on('change', '.clProduto', function() {
      let self = $(this)
      let pk = $(this).val()
      let url = '/produto/' + pk + '/json/'
    
      $.ajax({
        url: url,
        type: 'GET',
        success: function(response) {
          estoque = response.data[0].estoque
          campo = self.attr('id').replace('produto', 'quantidade')
          estoque_inicial = self.attr('id').replace('produto', 'inicial')
          // Estoque inicial
          $('#'+estoque_inicial).val(estoque)
          // Remove o valor do campo 'quantidade'
          $('#'+campo).val('')
        },
        error: function(xhr) {
          // body...
        }
      })
    });
    
    $(document).on('change', '.clQuantidade', function() {
        quantidade = $(this).val();
      // Aqui é feito o cálculo de soma do estoque
      // saldo = Number(quantidade) + Number(estoque);
      campo = $(this).attr('id').replace('quantidade', 'saldo')
      campo_estoque_inicial = $(this).attr('id').replace('quantidade', 'inicial')
      estoque_inicial = $('#'+campo_estoque_inicial).val()
      saldo = Number(quantidade) + Number(estoque_inicial)
      // Desabilita o 'Saldo'
      $('#'+campo).prop('type', 'hidden')
      // Atribui o saldo ao campo 'saldo'
      $('#'+campo).val(saldo)
      campo2 = $(this).attr('id').replace('quantidade', 'saldo-span')
      // Atrubui o saldo ao campo 'id_estoque-x-saldo-span'
      $('#'+campo2).text(saldo)
      
    });
    
    </script>

<script type="text/html" id="item-estoque">
    <div id="item-__prefix__" class="form-group">
        {{ formset.empty_form|bootstrap }}
      </div>
</script>

{% endblock js%}